### ISSUE TITLE
api/v1/patientsで取得できるデータにCSVの見出し行が含まれてます

### ISSUE THREAD

**Issue by otokunaga2** [RuiHirano/covid19-rader-for-japan-api#5]
> {"id":"コード,発表日,ソース,都道府県,居住地,年齢,性別,属性,県内No.,渡航・接触歴,詳細（渡航先、接触者、関与クラスター）,ID,確定診断日,発症日,\"症状(0:無症状,1:軽症・中等症,2:重症(ICU、人工呼吸器),3:検査時無症状)\",死亡/退院日,コメント,\"転帰(1:退院,2:死亡)\",転帰ソース,コメント_1,推定感染日","date":"","prefecture":"","residence":"","age":"","sex":"","attribute":"","prefecture_number":"","travel_or_contact":"","detail":"","src":"","onset":"","symptom":"","death_or_discharge_date":"","comment1":"","comment2":"","outcome":"","outcome_src":""},

上記のようなデータが現在APIで取得したデータに含まれてしまっているようです。
上記修正のためのPR作成して送らせてもらいました。

**Comment by RuiHirano** [comment]
PRをマージしましたのでCloseさせていただきます。
ありがとうございます。
